// <auto-generated />
using System;
using FoxDen.Web.Models.Recepie;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoxDen.Web.Migrations.Recepies
{
    [DbContext(typeof(RecepieDbContext))]
    [Migration("20251213183057_InitRecepie")]
    partial class InitRecepie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecepieGroups");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecepieImages");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecepieIngredients");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantityType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepieProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepieVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecepieProcessId");

                    b.HasIndex("RecepieVersionId");

                    b.ToTable("RecepieItems");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepieVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("RecepieVersionId");

                    b.ToTable("RecepieProcesses");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepieGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("RecepieGroupId");

                    b.ToTable("RecepieVersions");
                });

            modelBuilder.Entity("RecepieIngredientRecepieIngredient", b =>
                {
                    b.Property<int>("RecepieIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubstitutionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecepieIngredientId", "SubstitutionsId");

                    b.HasIndex("SubstitutionsId");

                    b.ToTable("RecepieIngredientSubstitutions", (string)null);
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieItem", b =>
                {
                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieIngredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieProcess", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecepieProcessId");

                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieVersion", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecepieVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieProcess", b =>
                {
                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieImage", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieVersion", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecepieVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieVersion", b =>
                {
                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieImage", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieGroup", null)
                        .WithMany("Versions")
                        .HasForeignKey("RecepieGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("RecepieIngredientRecepieIngredient", b =>
                {
                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieIngredient", null)
                        .WithMany()
                        .HasForeignKey("RecepieIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoxDen.Web.Models.Recepie.RecepieIngredient", null)
                        .WithMany()
                        .HasForeignKey("SubstitutionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieGroup", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieProcess", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FoxDen.Web.Models.Recepie.RecepieVersion", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
